name: ci

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PNPM_VERSION: 10
  NODE_VERSION: 24

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      VITE_SPAM: "spam"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm fmt
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm build
  vitest:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm test
  playwright:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm exec playwright install chromium --with-deps
      - run: pnpm e2e-test
  playwright-ct:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install
      - run: pnpm exec playwright install chromium --with-deps
      - run: pnpm ct-test
